-- ═══════════════════════════════════════════════════════════════
--  V1 — 초기 스키마
--
--  설계 원칙
--   1. 스키마의 소유자는 Flyway 다. Hibernate 는 validate 만 한다.
--   2. 개인정보는 최소 수집 + 암호화 + 만료 파기. 컬럼 단위로 명시한다.
--   3. 열거값은 TEXT + CHECK 로 둔다. DB 열거형은 값 추가가 번거롭고,
--      정수 코드는 DB 를 직접 볼 때 의미를 알 수 없다.
--   4. 모든 시각은 TIMESTAMPTZ. 서버 타임존이 바뀌어도 값이 흔들리지 않는다.
-- ═══════════════════════════════════════════════════════════════


-- ───────────────────────────────────────────────────────────────
--  제품
-- ───────────────────────────────────────────────────────────────
CREATE TABLE product (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- URL 에 노출된다. 한번 공개되면 바꾸기 어려우므로 불변으로 취급한다.
    slug            VARCHAR(120)  NOT NULL,
    name_ko         VARCHAR(120)  NOT NULL,
    name_en         VARCHAR(120)  NOT NULL,
    category        VARCHAR(20)   NOT NULL,

    -- 쇼케이스에서 제품명 아래 한 줄로 붙는다
    summary         VARCHAR(200)  NOT NULL DEFAULT '',
    -- 리치 텍스트. ★ 저장 시점에 살균된 HTML 만 들어와야 한다 (기획서 §11).
    description     TEXT          NOT NULL DEFAULT '',

    -- 치수. 설치 면적은 이 사이트의 핵심 소구점이라 NULL 을 허용하지 않는다.
    footprint_m2    NUMERIC(6, 2) NOT NULL,
    width_mm        INTEGER       NOT NULL,
    depth_mm        INTEGER       NOT NULL,
    height_mm       INTEGER       NOT NULL,
    weight_kg       NUMERIC(7, 2) NOT NULL,

    thumbnail_key   VARCHAR(255),
    sort_order      INTEGER       NOT NULL DEFAULT 0,
    visible         BOOLEAN       NOT NULL DEFAULT FALSE,

    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT uq_product_slug        UNIQUE (slug),
    CONSTRAINT ck_product_category    CHECK (category IN ('STRENGTH', 'CABLE', 'RACK', 'BENCH', 'CARDIO')),
    CONSTRAINT ck_product_slug_format CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
    CONSTRAINT ck_product_dimensions  CHECK (
        footprint_m2 > 0 AND width_mm > 0 AND depth_mm > 0 AND height_mm > 0 AND weight_kg > 0
    )
);

COMMENT ON COLUMN product.description IS '살균된 HTML 만 저장한다. 원문을 그대로 넣지 말 것.';
COMMENT ON COLUMN product.visible     IS '기본 FALSE. 실수로 미완성 제품이 공개되지 않게 한다.';

-- 공개 목록 조회는 항상 visible=TRUE + sort_order 정렬이다.
CREATE INDEX ix_product_visible_sort ON product (sort_order, id) WHERE visible;


CREATE TABLE product_image (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id   BIGINT       NOT NULL,
    image_key    VARCHAR(255) NOT NULL,
    alt_text     VARCHAR(200) NOT NULL DEFAULT '',
    sort_order   INTEGER      NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT fk_product_image_product
        FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE
);

CREATE INDEX ix_product_image_product ON product_image (product_id, sort_order);


-- ───────────────────────────────────────────────────────────────
--  소식
-- ───────────────────────────────────────────────────────────────
CREATE TABLE news (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug          VARCHAR(140) NOT NULL,
    title         VARCHAR(200) NOT NULL,
    -- ★ 살균된 HTML 만.
    body          TEXT         NOT NULL DEFAULT '',
    thumbnail_key VARCHAR(255),
    published_at  TIMESTAMPTZ,
    visible       BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uq_news_slug UNIQUE (slug),
    -- 공개하려면 발행일이 반드시 있어야 한다
    CONSTRAINT ck_news_published CHECK (NOT visible OR published_at IS NOT NULL)
);

CREATE INDEX ix_news_published ON news (published_at DESC) WHERE visible;


-- ───────────────────────────────────────────────────────────────
--  문의  ★ 개인정보를 담는 유일한 테이블
--
--  이 테이블 하나가 이 시스템에서 가장 위험한 자산이다 (기획서 §7).
--  유출 시 외부의 불법적 접근에 의한 것이면 건수와 무관하게
--  72시간 내 신고 의무가 발생한다.
-- ───────────────────────────────────────────────────────────────
CREATE TABLE inquiry (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    type              VARCHAR(20)  NOT NULL,

    name              VARCHAR(80)  NOT NULL,

    -- ★ AES-256-GCM 암호문(base64). 평문 전화번호를 여기 넣지 말 것.
    --   DB 가 통째로 유출돼도 즉시 악용되지 않게 하는 마지막 방어선이다.
    phone_encrypted   TEXT         NOT NULL,

    -- ★ 검색용 블라인드 인덱스.
    --   정규화한 번호(숫자만)의 HMAC-SHA256. 복호화가 불가능하면서
    --   "같은 번호인가"는 판별된다. 결정적 암호화를 쓰면 안 되는 이유는
    --   같은 평문이 같은 암호문이 되어 빈도 분석이 가능해지기 때문이다.
    phone_blind_index BYTEA,

    email             VARCHAR(160),
    company           VARCHAR(120),
    region            VARCHAR(60),
    message           TEXT         NOT NULL DEFAULT '',

    status            VARCHAR(20)  NOT NULL DEFAULT 'NEW',
    -- 관리자 내부 메모. 정보주체 열람 청구 대상이 될 수 있으므로
    -- 주관적 평가를 적지 않도록 관리 화면에 안내를 띄운다.
    memo              TEXT         NOT NULL DEFAULT '',

    -- ── 법적 요건 (기획서 §14) ──
    -- 수집·이용 동의 시각. NULL 이면 애초에 저장돼선 안 된다.
    consent_at        TIMESTAMPTZ  NOT NULL,
    -- 마케팅 활용 동의는 반드시 별도 항목이다. 선택이므로 NULL 허용.
    marketing_consent_at TIMESTAMPTZ,
    -- 보유기간 만료 시각. 배치가 이 값을 지난 행을 파기한다.
    purge_at          TIMESTAMPTZ  NOT NULL,

    -- 스팸 분석용. 개인정보이므로 파기 대상에 함께 포함된다.
    source_ip         INET,
    user_agent        VARCHAR(400),

    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT ck_inquiry_type   CHECK (type IN ('QUOTE', 'DEMO', 'OFFICIAL', 'ETC')),
    CONSTRAINT ck_inquiry_status CHECK (status IN ('NEW', 'CONTACTING', 'DONE', 'SPAM')),
    CONSTRAINT ck_inquiry_purge  CHECK (purge_at > consent_at)
);

COMMENT ON TABLE  inquiry                   IS '개인정보 포함. 접근 권한 최소화 + 조회 이력 로깅 대상.';
COMMENT ON COLUMN inquiry.phone_encrypted   IS 'AES-256-GCM(base64). 평문 금지.';
COMMENT ON COLUMN inquiry.phone_blind_index IS 'HMAC-SHA256(정규화 번호). 검색 전용.';
COMMENT ON COLUMN inquiry.purge_at          IS '자동 파기 기준 시각. 배치가 매일 확인한다.';

-- 관리 화면 기본 목록: 상태별 최신순
CREATE INDEX ix_inquiry_status_created ON inquiry (status, created_at DESC);
-- 전화번호 검색
CREATE INDEX ix_inquiry_phone_blind    ON inquiry (phone_blind_index);
-- 파기 배치가 매일 스캔한다. 부분 인덱스로 대상만 좁힌다.
CREATE INDEX ix_inquiry_purge          ON inquiry (purge_at);


-- 문의 ↔ 제품 (docs/OPEN-DECISIONS.md D-4)
-- 단일 컬럼에 ID 목록을 넣지 않는다. "어떤 제품 문의가 많은가"는
-- 기획서 §1.2 의 2차 KPI 이므로 반드시 집계하게 된다.
CREATE TABLE inquiry_product (
    inquiry_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,

    PRIMARY KEY (inquiry_id, product_id),
    CONSTRAINT fk_inquiry_product_inquiry
        FOREIGN KEY (inquiry_id) REFERENCES inquiry (id) ON DELETE CASCADE,
    -- 제품이 지워져도 문의 기록은 남아야 하지만, 어떤 제품이었는지는
    -- 알 수 없게 된다. 제품은 삭제 대신 visible=FALSE 로 운영한다.
    CONSTRAINT fk_inquiry_product_product
        FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE
);

CREATE INDEX ix_inquiry_product_product ON inquiry_product (product_id);


-- ───────────────────────────────────────────────────────────────
--  사이트 설정
-- ───────────────────────────────────────────────────────────────
CREATE TABLE site_setting (
    key        VARCHAR(80)  PRIMARY KEY,
    value      TEXT         NOT NULL DEFAULT '',
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);


-- ───────────────────────────────────────────────────────────────
--  관리자 계정
-- ───────────────────────────────────────────────────────────────
CREATE TABLE admin_user (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(60)  NOT NULL,
    -- ★ BCrypt 해시만. 평문·MD5·SHA 금지 (기획서 §10).
    --   MD5 는 GPU 로 초당 수십억 건 대입이 가능해 사실상 평문과 같다.
    password_hash   VARCHAR(100) NOT NULL,
    display_name    VARCHAR(60)  NOT NULL DEFAULT '',
    role            VARCHAR(20)  NOT NULL DEFAULT 'ADMIN',
    enabled         BOOLEAN      NOT NULL DEFAULT TRUE,

    -- TOTP 2FA. 시크릿은 암호화해서 저장한다.
    totp_secret_encrypted TEXT,
    totp_enabled    BOOLEAN      NOT NULL DEFAULT FALSE,

    last_login_at   TIMESTAMPTZ,
    last_login_ip   INET,
    password_changed_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uq_admin_user_username UNIQUE (username),
    CONSTRAINT ck_admin_user_role     CHECK (role IN ('ADMIN', 'EDITOR')),
    -- BCrypt 해시는 항상 $2a$/$2b$/$2y$ 로 시작한다.
    -- 다른 알고리즘이 섞여 들어오면 DB 가 거부한다.
    CONSTRAINT ck_admin_user_bcrypt   CHECK (password_hash ~ '^\$2[aby]\$')
);


-- Refresh Token 은 DB 에 두고 로그아웃 시 무효화한다 (기획서 §10).
-- 토큰 자체가 아니라 해시를 저장한다 — DB 유출만으로 세션을 탈취당하지
-- 않게 하기 위해서다.
CREATE TABLE admin_refresh_token (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_user_id BIGINT       NOT NULL,
    token_hash    BYTEA        NOT NULL,
    issued_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    expires_at    TIMESTAMPTZ  NOT NULL,
    revoked_at    TIMESTAMPTZ,
    -- 재사용 감지: 이미 회전된 토큰이 다시 오면 탈취로 간주하고
    -- 해당 사용자의 모든 세션을 끊는다.
    replaced_by   BIGINT,
    user_agent    VARCHAR(400),
    ip            INET,

    CONSTRAINT uq_admin_refresh_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_admin_refresh_token_user
        FOREIGN KEY (admin_user_id) REFERENCES admin_user (id) ON DELETE CASCADE,
    CONSTRAINT fk_admin_refresh_token_replaced
        FOREIGN KEY (replaced_by) REFERENCES admin_refresh_token (id) ON DELETE SET NULL
);

CREATE INDEX ix_admin_refresh_token_user    ON admin_refresh_token (admin_user_id);
CREATE INDEX ix_admin_refresh_token_expires ON admin_refresh_token (expires_at);


-- 로그인 시도 기록.
-- 계정 전면 잠금만 두면 공격자가 아무 비밀번호나 반복해 대표님을
-- 상시 차단할 수 있다(가용성 DoS). IP 기준을 1차 방어로 삼는다.
CREATE TABLE login_attempt (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username     VARCHAR(60)  NOT NULL,
    ip           INET         NOT NULL,
    successful   BOOLEAN      NOT NULL,
    user_agent   VARCHAR(400),
    attempted_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX ix_login_attempt_ip   ON login_attempt (ip, attempted_at DESC);
CREATE INDEX ix_login_attempt_user ON login_attempt (username, attempted_at DESC);


-- ───────────────────────────────────────────────────────────────
--  감사 로그
--
--  사고가 났을 때 유일한 단서다 (기획서 §13).
--  개인정보 조회·CSV 내보내기도 반드시 여기에 남긴다 —
--  컬럼 암호화를 무력화하는 통로가 CSV 내보내기이기 때문이다.
-- ───────────────────────────────────────────────────────────────
CREATE TABLE admin_audit_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_user_id BIGINT,
    -- 계정이 지워져도 로그는 남아야 하므로 이름을 문자열로 함께 박아둔다
    admin_username VARCHAR(60) NOT NULL DEFAULT '',
    action        VARCHAR(60)  NOT NULL,
    target_type   VARCHAR(40),
    target_id     VARCHAR(60),
    -- 변경 요약. ★ 여기에 비밀번호·토큰·전화번호 평문을 넣지 말 것.
    detail        TEXT         NOT NULL DEFAULT '',
    ip            INET,
    user_agent    VARCHAR(400),
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT fk_admin_audit_log_user
        FOREIGN KEY (admin_user_id) REFERENCES admin_user (id) ON DELETE SET NULL
);

CREATE INDEX ix_admin_audit_log_created ON admin_audit_log (created_at DESC);
CREATE INDEX ix_admin_audit_log_action  ON admin_audit_log (action, created_at DESC);

COMMENT ON TABLE admin_audit_log IS '보관 기간 최소 3개월. 개인정보 조회·내보내기도 기록한다.';
