-- ═══════════════════════════════════════════════════════════════
--  V3 — 품목 종류 확장 · 중고 · 공식 헬스장
--
--  V1/V2 는 수정하지 않는다. 이미 적용된 마이그레이션을 고치면
--  적용한 곳과 적용하지 않은 곳의 스키마가 갈라진다.
-- ═══════════════════════════════════════════════════════════════


-- ───────────────────────────────────────────────────────────────
--  1. product 에 품목 종류 추가
--
--  기구 / 부품 / 악세사리를 한 테이블에서 다룬다.
--  셋은 이름·이미지·설명·정렬·공개여부가 동일하고, 다른 것은
--  "치수가 의미 있는가" 뿐이다. 테이블을 나누면 관리 화면과
--  이미지 파이프라인을 세 벌 만들게 된다.
-- ───────────────────────────────────────────────────────────────

ALTER TABLE product
    ADD COLUMN type VARCHAR(20) NOT NULL DEFAULT 'EQUIPMENT';

ALTER TABLE product
    ADD CONSTRAINT ck_product_type
        CHECK (type IN ('EQUIPMENT', 'PART', 'ACCESSORY'));

-- 부품·악세사리 카테고리를 허용 목록에 추가한다
ALTER TABLE product DROP CONSTRAINT ck_product_category;
ALTER TABLE product
    ADD CONSTRAINT ck_product_category
        CHECK (category IN ('STRENGTH', 'CABLE', 'RACK', 'BENCH', 'CARDIO',
                            'PART', 'ACCESSORY'));

/*
 * 치수는 기구에만 요구한다.
 *
 * V1 에서 NOT NULL 이었던 컬럼들을 완화하되, 그냥 푸는 것이 아니라
 * "기구라면 반드시 있어야 한다" 는 조건부 제약으로 바꾼다.
 * 설치 면적이 비어 있는 기구가 공개되는 것을 DB 가 막는다 —
 * 이 사이트가 파는 것이 그 숫자이기 때문이다.
 */
ALTER TABLE product ALTER COLUMN footprint_m2 DROP NOT NULL;
ALTER TABLE product ALTER COLUMN width_mm     DROP NOT NULL;
ALTER TABLE product ALTER COLUMN depth_mm     DROP NOT NULL;
ALTER TABLE product ALTER COLUMN height_mm    DROP NOT NULL;
ALTER TABLE product ALTER COLUMN weight_kg    DROP NOT NULL;

ALTER TABLE product DROP CONSTRAINT ck_product_dimensions;
ALTER TABLE product
    ADD CONSTRAINT ck_product_dimensions
        CHECK (
            CASE WHEN type = 'EQUIPMENT'
                 THEN footprint_m2 IS NOT NULL AND footprint_m2 > 0
                      AND width_mm  IS NOT NULL AND width_mm  > 0
                      AND depth_mm  IS NOT NULL AND depth_mm  > 0
                      AND height_mm IS NOT NULL AND height_mm > 0
                 ELSE (footprint_m2 IS NULL OR footprint_m2 > 0)
                      AND (width_mm  IS NULL OR width_mm  > 0)
                      AND (depth_mm  IS NULL OR depth_mm  > 0)
                      AND (height_mm IS NULL OR height_mm > 0)
            END
            AND (weight_kg IS NULL OR weight_kg > 0)
        );

COMMENT ON COLUMN product.type IS 'EQUIPMENT 만 설치 면적이 필수다.';

-- 목록 조회는 항상 type + visible 로 좁힌다
DROP INDEX IF EXISTS ix_product_visible_sort;
CREATE INDEX ix_product_visible_type_sort
    ON product (type, sort_order, id) WHERE visible;


-- ───────────────────────────────────────────────────────────────
--  2. 중고 매물
--
--  카탈로그가 아니라 "개별 물건" 이다.
--  같은 파워 랙이라도 2019년식 A 와 2022년식 B 는 다른 매물이고,
--  하나가 팔려도 다른 하나는 남는다. product 로는 표현되지 않는다.
--
--  product_id 로 카탈로그와 느슨하게 연결해 두면
--  "파워 랙 중고 있나요" 를 답할 수 있다. 단종된 모델은 NULL 이다.
-- ───────────────────────────────────────────────────────────────
CREATE TABLE used_item (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    slug            VARCHAR(140)  NOT NULL,
    -- 카탈로그 제품과의 연결. 단종 모델이면 NULL 이다.
    product_id      BIGINT,

    name_ko         VARCHAR(140)  NOT NULL,
    -- 제품이 지워져도 무엇이었는지는 남아야 한다
    model_name      VARCHAR(140)  NOT NULL DEFAULT '',

    condition_grade VARCHAR(10)   NOT NULL,
    -- 제조/사용 연식. 정확한 날짜를 모르는 경우가 많아 연도만 받는다.
    year_made       SMALLINT,
    -- 가격은 협의가 기본이다. NULL 이면 화면에 "가격 문의" 로 표시한다.
    price_krw       INTEGER,

    description     TEXT          NOT NULL DEFAULT '',
    thumbnail_key   VARCHAR(255),

    status          VARCHAR(20)   NOT NULL DEFAULT 'AVAILABLE',
    -- 재고 수량. 같은 상태의 물건이 여러 대일 수 있다.
    quantity        SMALLINT      NOT NULL DEFAULT 1,

    sort_order      INTEGER       NOT NULL DEFAULT 0,
    visible         BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT uq_used_item_slug UNIQUE (slug),
    CONSTRAINT fk_used_item_product
        FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE SET NULL,
    CONSTRAINT ck_used_item_condition
        CHECK (condition_grade IN ('A', 'B', 'C')),
    CONSTRAINT ck_used_item_status
        CHECK (status IN ('AVAILABLE', 'RESERVED', 'SOLD')),
    CONSTRAINT ck_used_item_price    CHECK (price_krw IS NULL OR price_krw > 0),
    CONSTRAINT ck_used_item_quantity CHECK (quantity >= 0),
    CONSTRAINT ck_used_item_year
        CHECK (year_made IS NULL OR (year_made BETWEEN 1980 AND 2100))
);

COMMENT ON TABLE  used_item                 IS '개별 중고 매물. 카탈로그(product)와 다르다.';
COMMENT ON COLUMN used_item.condition_grade IS 'A 상급 / B 중급 / C 하급. 기준은 관리 화면에 안내한다.';
COMMENT ON COLUMN used_item.price_krw       IS 'NULL 이면 "가격 문의"로 표시한다.';

-- 공개 목록: 판매완료를 뒤로 보내되 목록에서 지우지는 않는다
-- (팔린 것도 보여야 "물건이 도는 곳"으로 읽힌다)
CREATE INDEX ix_used_item_visible ON used_item (status, sort_order, id) WHERE visible;
CREATE INDEX ix_used_item_product ON used_item (product_id);


CREATE TABLE used_item_image (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    used_item_id BIGINT       NOT NULL,
    image_key    VARCHAR(255) NOT NULL,
    alt_text     VARCHAR(200) NOT NULL DEFAULT '',
    sort_order   INTEGER      NOT NULL DEFAULT 0,

    CONSTRAINT fk_used_item_image_item
        FOREIGN KEY (used_item_id) REFERENCES used_item (id) ON DELETE CASCADE
);

CREATE INDEX ix_used_item_image_item ON used_item_image (used_item_id, sort_order);


-- ───────────────────────────────────────────────────────────────
--  3. 짐레코 공식 헬스장
--
--  ⚠️ 여기에는 사업자 정보가 들어간다. 개인이 운영하는 소규모
--     센터라면 대표자명·연락처가 개인정보에 해당할 수 있다.
--     그래서 게재 동의 시각을 컬럼으로 강제한다 — 동의 없이
--     연락처를 공개 사이트에 올리는 일이 생기지 않도록.
-- ───────────────────────────────────────────────────────────────
CREATE TABLE official_center (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    slug          VARCHAR(140) NOT NULL,
    name          VARCHAR(140) NOT NULL,

    region        VARCHAR(40)  NOT NULL,
    address       VARCHAR(255) NOT NULL DEFAULT '',
    -- 지도 표시용. 좌표가 없으면 목록에만 노출한다.
    latitude      NUMERIC(9, 6),
    longitude     NUMERIC(9, 6),

    phone         VARCHAR(40)  NOT NULL DEFAULT '',
    website_url   VARCHAR(255) NOT NULL DEFAULT '',
    instagram_url VARCHAR(255) NOT NULL DEFAULT '',

    -- 규모·도입 기구 등 소개
    summary       VARCHAR(200) NOT NULL DEFAULT '',
    description   TEXT         NOT NULL DEFAULT '',
    area_pyeong   SMALLINT,
    opened_at     DATE,

    thumbnail_key VARCHAR(255),

    -- ★ 게재 동의. 없으면 공개할 수 없다.
    consent_at    TIMESTAMPTZ,

    sort_order    INTEGER      NOT NULL DEFAULT 0,
    visible       BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uq_official_center_slug UNIQUE (slug),
    -- 동의 없이 공개 상태가 될 수 없다
    CONSTRAINT ck_official_center_consent
        CHECK (NOT visible OR consent_at IS NOT NULL),
    CONSTRAINT ck_official_center_area
        CHECK (area_pyeong IS NULL OR area_pyeong > 0),
    CONSTRAINT ck_official_center_coords
        CHECK ((latitude IS NULL) = (longitude IS NULL))
);

COMMENT ON COLUMN official_center.consent_at IS
    '센터의 게재 동의 시각. 없으면 공개 불가 (CHECK 제약).';

CREATE INDEX ix_official_center_visible ON official_center (region, sort_order, id) WHERE visible;


CREATE TABLE official_center_image (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    official_center_id BIGINT       NOT NULL,
    image_key          VARCHAR(255) NOT NULL,
    alt_text           VARCHAR(200) NOT NULL DEFAULT '',
    sort_order         INTEGER      NOT NULL DEFAULT 0,

    CONSTRAINT fk_official_center_image_center
        FOREIGN KEY (official_center_id) REFERENCES official_center (id) ON DELETE CASCADE
);

CREATE INDEX ix_official_center_image_center
    ON official_center_image (official_center_id, sort_order);


-- ───────────────────────────────────────────────────────────────
--  4. 문의 유형 확장
--
--  중고 문의와 부품 문의는 응대 방식이 다르다.
--  유형이 섞여 있으면 대표님이 접수함에서 매번 본문을 읽어야 한다.
-- ───────────────────────────────────────────────────────────────
ALTER TABLE inquiry DROP CONSTRAINT ck_inquiry_type;
ALTER TABLE inquiry
    ADD CONSTRAINT ck_inquiry_type
        CHECK (type IN ('QUOTE', 'DEMO', 'OFFICIAL', 'USED', 'PART', 'ETC'));
