-- ═══════════════════════════════════════════════════════════════
--  V7 — 배너 · 섹션 이미지 · FAQ · 공지
--
--  관리 화면에서 등록할 것들이 늘어났다. 네 가지를 한 번에 만든다.
-- ═══════════════════════════════════════════════════════════════

-- ───────────────────────────────────────────────────────────────
--  1. 배너 — 각 페이지 히어로에 깔린다
--
--  ★ PC 와 모바일 이미지를 둘 다 필수로 받는다.
--
--    한 장으로 양쪽을 덮으면 반드시 한쪽이 깨진다. 가로로 넓은 사진을
--    세로 화면에 넣으면 좌우가 잘려 기구가 프레임 밖으로 나가고,
--    세로 사진을 데스크톱에 늘리면 화질이 무너진다.
--    "나중에 채우겠다" 로 비워 두면 그 상태로 배포되므로 NOT NULL 로 막는다.
--
--  ★ 위치는 문자열이 아니라 CHECK 로 고정한다.
--    관리 화면 드롭다운과 값이 어긋나면 배너가 어디에도 안 뜬다.
-- ───────────────────────────────────────────────────────────────
CREATE TABLE banner (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- 어느 페이지 히어로에 깔리는가
    position         VARCHAR(20)  NOT NULL,

    -- 배경 이미지 — 둘 다 필수
    image_pc_key     VARCHAR(255) NOT NULL,
    image_mobile_key VARCHAR(255) NOT NULL,

    -- 이미지 위에 얹는 글. 비우면 이미지만 보인다.
    title            VARCHAR(120) NOT NULL DEFAULT '',
    subtitle         VARCHAR(200) NOT NULL DEFAULT '',
    link_url         VARCHAR(255) NOT NULL DEFAULT '',

    -- 노출 기간. 비우면 제한 없음 (행사 배너를 미리 등록해 둘 수 있게)
    starts_at        TIMESTAMPTZ,
    ends_at          TIMESTAMPTZ,

    sort_order       INTEGER      NOT NULL DEFAULT 0,
    visible          BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT ck_banner_position CHECK (position IN
        ('MAIN', 'PRODUCT', 'USED', 'PART', 'ACCESSORY', 'CENTER')),
    CONSTRAINT ck_banner_period CHECK (ends_at IS NULL OR starts_at IS NULL OR ends_at > starts_at)
);

COMMENT ON COLUMN banner.position IS
    '메인 / 제품 / 중고 / 부품 / 악세사리 / 공식 헬스장. 관리 화면 드롭다운과 같은 값이어야 한다.';

-- 한 위치에 여러 장을 두고 순서대로 돌릴 수 있게 유니크를 걸지 않는다
CREATE INDEX ix_banner_position ON banner (position, sort_order, id) WHERE visible;


-- ───────────────────────────────────────────────────────────────
--  2. 섹션 이미지 — 메인의 고정 구역에 들어가는 사진
--
--  "왜 짐레코인가" 3단 구역과 "공간을 알려주시면" 배경처럼,
--  구역 자체는 코드에 고정돼 있고 사진만 바뀌는 자리다.
--  제품처럼 개수가 늘지 않으므로 키(section_key)로 한 줄씩 잡는다.
--
--  배너와 마찬가지로 PC · 모바일 둘 다 필수다.
-- ───────────────────────────────────────────────────────────────
CREATE TABLE section_media (
    section_key      VARCHAR(60)  PRIMARY KEY,
    image_pc_key     VARCHAR(255) NOT NULL,
    image_mobile_key VARCHAR(255) NOT NULL,
    alt_text         VARCHAR(200) NOT NULL DEFAULT '',
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now()
);

COMMENT ON TABLE section_media IS
    '메인의 고정 구역 배경/이미지. 구역이 늘면 여기에 키를 추가한다.';


-- ───────────────────────────────────────────────────────────────
--  3. FAQ — 고객센터
--
--  아코디언으로 펼쳐 보는 형태라 목록에서 답변까지 한 번에 내려준다.
--  답변은 살균된 HTML 만 들어간다 (링크·줄바꿈 정도는 필요하다).
-- ───────────────────────────────────────────────────────────────
CREATE TABLE faq (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category   VARCHAR(40)  NOT NULL DEFAULT '일반',
    question   VARCHAR(200) NOT NULL,
    answer     TEXT         NOT NULL DEFAULT '',
    sort_order INTEGER      NOT NULL DEFAULT 0,
    visible    BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX ix_faq_visible ON faq (category, sort_order, id) WHERE visible;


-- ───────────────────────────────────────────────────────────────
--  4. 공지사항 — 고객센터
--
--  ★ news(소식) 와 따로 둔다.
--    소식은 "신제품 입고·행사" 로 브랜드 메뉴에 있고,
--    공지는 "서비스 점검·배송 지연" 으로 고객센터 메뉴에 있다.
--    보는 사람도 찾는 자리도 달라서 한 게시판에 섞으면
--    둘 다 신뢰를 잃는다. 합치기로 하면 이 표를 지우고
--    news 에 category 를 더하면 된다.
-- ───────────────────────────────────────────────────────────────
CREATE TABLE notice (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(200) NOT NULL,
    body         TEXT         NOT NULL DEFAULT '',

    -- 위로 고정. 점검 공지처럼 기간 내내 맨 위에 있어야 하는 글이 있다.
    pinned       BOOLEAN      NOT NULL DEFAULT FALSE,

    published_at TIMESTAMPTZ,
    visible      BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),

    -- 공개하려면 발행일이 반드시 있어야 한다 (news 와 같은 규칙)
    CONSTRAINT ck_notice_published CHECK (NOT visible OR published_at IS NOT NULL)
);

CREATE INDEX ix_notice_published
    ON notice (pinned DESC, published_at DESC) WHERE visible;


-- ───────────────────────────────────────────────────────────────
--  5. 사이트 설정 — 관리 화면에서 쓸 키를 미리 심는다
--
--  값이 비어 있으면 화면이 그 항목을 아예 내보내지 않는다.
--  키가 없으면 관리 화면에 칸이 안 뜨므로 여기서 만들어 둔다.
-- ───────────────────────────────────────────────────────────────
INSERT INTO site_setting (key, value) VALUES
    ('support.faq_intro',      ''),
    ('support.notice_intro',   ''),
    ('home.section_why_title', '왜 짐레코인가'),
    ('theme.default',          'dark')
ON CONFLICT (key) DO NOTHING;

COMMENT ON COLUMN site_setting.value IS
    '빈 문자열이면 화면에서 해당 항목을 표시하지 않는다.';
