-- ═══════════════════════════════════════════════════════════════
--  V8 — 모델번호 · 기구 한 대(일련번호) · 조회 이력
--
--  ── 두 가지는 다른 것이다 ──
--
--    모델번호(model_code)  제품 «종류» 를 가리킨다. 제품당 하나.  350, Gi-020
--    일련번호(serial)      «그 한 대» 를 가리킨다. 같은 모델에 수십 개.
--
--  모델번호는 product 의 칸이고, 일련번호는 별도의 표다.
--  한 제품에 여러 대가 달리므로 칸으로 넣을 수 없다.
--
--  ── 이 표가 막으려는 것: 이미테이션 ──
--
--  ★ 「번호가 등록돼 있다」 는 정품 증명이 아니다.
--    위조범은 진짜 기구의 명판을 찍어 같은 번호를 여러 대에 붙인다.
--    번호 존재 여부만 답하면 우리 시스템이 가짜를 인증해 주는 꼴이 된다.
--    그래서 조회 응답은 «이 번호의 기구는 어떤 모델 · 몇 년산인가» 를 함께
--    돌려준다. 눈앞의 기구와 대조하게 만드는 것이 실제 방어다.
--
--  ★ 진짜 신호는 조회 이력에 있다.
--    같은 번호가 서로 다른 곳에서 반복 조회되면 그것이 복제 신호다.
--    이력을 남기지 않으면 이 신호를 영영 볼 수 없다. 그래서 조회 이력을
--    «성공·실패 모두» 남긴다 — 실패가 몰리는 것은 번호 긁어가기다.
-- ═══════════════════════════════════════════════════════════════


-- ── 1. 모델번호 ────────────────────────────────────────────────
--
-- VARCHAR 다. 정수로 잡으면 안 된다 — 확인된 것만 「350」 「116」 「Gi-020」
-- 「028028」 로 형식이 섞여 있고, 앞자리 0 이 사라지면 다른 번호가 된다.
--
-- 부분 유니크 인덱스를 쓴다. 아직 번호를 못 받은 제품이 많아 NULL 을
-- 허용해야 하는데, 일반 UNIQUE 제약은 NULL 을 여럿 허용하므로 그대로 써도
-- 되지만 «번호가 있는 것끼리만 유일» 이라는 의도를 인덱스에 드러낸다.

ALTER TABLE product
    ADD COLUMN model_code VARCHAR(40);

CREATE UNIQUE INDEX uq_product_model_code
    ON product (model_code)
    WHERE model_code IS NOT NULL;

COMMENT ON COLUMN product.model_code IS
    '본사 모델번호. 제품 종류의 식별자이며 일련번호가 아니다.';


-- ── 2. 기구 한 대 ──────────────────────────────────────────────

CREATE TABLE machine_unit (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    product_id  BIGINT       NOT NULL,

    -- 명판에 적힌 표기 그대로 보관한다. 사람에게 보여 줄 때 이 값을 쓴다.
    serial      VARCHAR(60)  NOT NULL,

    /*
     * 조회용 정규화 값 — 대문자 + 영숫자만.
     *
     * 명판을 손으로 옮겨 적으면 하이픈 · 공백 · 대소문자가 제각각이 된다.
     * 「gi-020-0117」 「GI 020 0117」 「Gi0200117」 이 같은 기구다.
     * 원본으로 비교하면 셋 다 «없는 번호» 가 되어, 정품을 가짜로 답한다.
     *
     * 표현식 인덱스가 아니라 실제 칸으로 둔다 — 애플리케이션이 같은 규칙으로
     * 만들어 넣어야 «저장할 때와 찾을 때의 규칙» 이 갈라지지 않는다.
     */
    serial_norm VARCHAR(60)  NOT NULL,

    made_year   SMALLINT,

    /*
     * 상태.
     *   REGISTERED 번호만 발급됨      SHIPPED  출고
     *   INSTALLED  설치 완료          RECOVERED 회수(중고로 돌아옴)
     *   SCRAPPED   폐기               FLAGGED  확인 필요(도난 신고 등)
     *
     * ★ FLAGGED 를 공개 화면에서 «도난» 이라고 말하지 않는다.
     *   훔친 사람이 조회해 보고 처분 경로를 바꾼다. 공개 응답은
     *   「확인이 필요합니다 — 연락 주세요」 로 받고 관리자에게 알린다.
     */
    status      VARCHAR(20)  NOT NULL DEFAULT 'REGISTERED',

    /*
     * 어느 센터에 있는가.
     *
     * ★ 공개 응답에 절대 넣지 않는다.
     *   어느 헬스장에 무엇이 몇 대 있는지는 그 센터의 영업 정보이고,
     *   장물 표적 목록이 되기도 한다. 관리 화면 안쪽 전용이다.
     */
    center_id   BIGINT,

    note        VARCHAR(300) NOT NULL DEFAULT '',

    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT machine_unit_pkey        PRIMARY KEY (id),
    CONSTRAINT uq_machine_unit_serial   UNIQUE (serial_norm),
    CONSTRAINT ck_machine_unit_status   CHECK (status IN
        ('REGISTERED', 'SHIPPED', 'INSTALLED', 'RECOVERED', 'SCRAPPED', 'FLAGGED')),
    -- 본사 설립이 1994년이다. 그 이전 연식은 입력 실수다.
    CONSTRAINT ck_machine_unit_year     CHECK (made_year IS NULL OR made_year BETWEEN 1994 AND 2100),
    CONSTRAINT ck_machine_unit_serial   CHECK (length(btrim(serial)) > 0 AND length(serial_norm) > 0),

    CONSTRAINT fk_machine_unit_product
        FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE RESTRICT,
    CONSTRAINT fk_machine_unit_center
        FOREIGN KEY (center_id) REFERENCES official_center (id) ON DELETE SET NULL
);

-- 제품을 지울 때 기구 대장이 조용히 사라지면 안 된다 → ON DELETE RESTRICT.
-- 센터는 사라져도 기구는 남는다 → SET NULL.

CREATE INDEX ix_machine_unit_product ON machine_unit (product_id, serial_norm);
CREATE INDEX ix_machine_unit_status  ON machine_unit (status, updated_at DESC);
CREATE INDEX ix_machine_unit_center  ON machine_unit (center_id) WHERE center_id IS NOT NULL;

COMMENT ON TABLE  machine_unit IS '기구 한 대. 일련번호는 대외 노출 시 최소 정보만 돌려준다.';
COMMENT ON COLUMN machine_unit.center_id IS '비공개. 공개 API 응답에 포함하지 않는다.';


-- ── 3. 조회 이력 ───────────────────────────────────────────────
--
-- 이 표가 이 기능의 값어치다. 번호 확인 자체는 누구나 만들 수 있지만,
-- «같은 번호가 서로 다른 곳에서 반복 조회된다» 는 사실은 이력이 있어야 보인다.
--
-- 실패도 남긴다. 없는 번호 조회가 한 곳에서 몰리는 것은 번호 긁어가기다.

CREATE TABLE machine_unit_lookup (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY,

    -- 없는 번호를 조회한 기록도 남기므로 NULL 을 허용한다.
    machine_unit_id BIGINT,

    -- 입력한 번호 «그대로». 오타 패턴 자체가 단서가 된다.
    serial_tried    VARCHAR(60)  NOT NULL,

    --   FOUND      번호와 모델이 맞음
    --   MISMATCH   번호는 있으나 함께 넣은 모델이 다름 → 가장 강한 위조 신호
    --   NOT_FOUND  없는 번호
    result          VARCHAR(20)  NOT NULL,

    -- VARCHAR(45) — IPv6 최대 표기 길이 (V5 와 같은 이유)
    source_ip       VARCHAR(45),
    user_agent      VARCHAR(300) NOT NULL DEFAULT '',

    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT machine_unit_lookup_pkey  PRIMARY KEY (id),
    CONSTRAINT ck_machine_unit_lookup_result CHECK (result IN ('FOUND', 'MISMATCH', 'NOT_FOUND')),
    CONSTRAINT fk_machine_unit_lookup_unit
        FOREIGN KEY (machine_unit_id) REFERENCES machine_unit (id) ON DELETE SET NULL
);

-- 「이 번호가 언제 어디서 조회됐나」 — 복제 판단의 기본 조회
CREATE INDEX ix_machine_unit_lookup_unit ON machine_unit_lookup (machine_unit_id, created_at DESC)
    WHERE machine_unit_id IS NOT NULL;

-- IP 당 조회 횟수 제한 (문의 접수와 같은 방식)
CREATE INDEX ix_machine_unit_lookup_ip   ON machine_unit_lookup (source_ip, created_at DESC);

-- 관리 화면의 「최근 조회」 목록
CREATE INDEX ix_machine_unit_lookup_recent ON machine_unit_lookup (created_at DESC);

COMMENT ON TABLE machine_unit_lookup IS
    '정품 확인 조회 이력. 접속 IP 를 담으므로 보존기간을 두고 파기한다 (개인정보처리방침 자동수집 항목).';
