-- ═══════════════════════════════════════════════════════════════
--  V9 — 판매 업체 · 판매/설치/보증 일자 · 사후 관리 이력
--
--  V8 은 「이 번호가 진짜인가」 까지였다. 여기서 「누구에게 팔렸고
--  그 뒤 무슨 일이 있었나」 를 더한다.
--
--  ── 왜 업체를 표로 빼는가 ──
--
--  machine_unit 에 상호·연락처를 칸으로 달면, 한 업체가 20대를 살 때
--  같은 상호가 20번 중복된다. 상호가 바뀌면 20곳을 고쳐야 하고, 한 곳을
--  놓치면 같은 업체가 둘로 보인다.
--
--  그리고 사후 관리의 기본 조회가 「이 업체가 산 기구 전부」 다.
--  칸으로 두면 상호 문자열 비교로 묶어야 하는데, 「○○피트니스」 와
--  「○○ 피트니스」 가 갈라진다.
--
--  ── V8 의 center_id 를 옮긴다 ──
--
--  V8 은 기구에 공식 헬스장을 직접 달았다. 그런데 실제 구매처는 대부분
--  공식 헬스장이 아니다(공식 헬스장은 게재 동의를 받은 일부일 뿐이다).
--  소유는 업체가 갖고, 그 업체가 공식 헬스장이기도 하면 거기서 잇는다.
--  V8 배포 직후이고 이 표에 데이터가 없어 지금 옮기는 것이 가장 싸다.
-- ═══════════════════════════════════════════════════════════════


-- ── 1. 판매 업체 ───────────────────────────────────────────────

CREATE TABLE machine_owner (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY,

    name         VARCHAR(140) NOT NULL,                  -- 상호
    region       VARCHAR(40)  NOT NULL DEFAULT '',
    address      VARCHAR(200) NOT NULL DEFAULT '',
    contact_name VARCHAR(60)  NOT NULL DEFAULT '',       -- 담당자

    /*
     * 연락처는 문의(inquiry)와 같은 방식으로 다룬다.
     *   phone_encrypted   AES-256-GCM 로 암호화한 값
     *   phone_blind_index HMAC — 「이 번호로 찾기」 를 위한 결정적 지문
     *
     * ★ 결정적 암호화를 쓰지 않는다. 같은 번호가 같은 암호문이 되면
     *   암호화한 의미가 없다. 찾기는 블라인드 인덱스가 맡는다.
     */
    phone_encrypted   TEXT   NOT NULL DEFAULT '',
    phone_blind_index BYTEA,

    /* 이 업체가 공식 헬스장이기도 하면 거기서 잇는다. 대부분 NULL 이다. */
    center_id    BIGINT,

    note         VARCHAR(300) NOT NULL DEFAULT '',
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT machine_owner_pkey PRIMARY KEY (id),
    CONSTRAINT ck_machine_owner_name CHECK (length(btrim(name)) > 0),

    /*
     * ★ 평문 전화번호가 들어오는 것을 DB 가 막는다.
     *   admin_user 의 BCrypt 제약과 같은 취지다 — 애플리케이션이 한 번
     *   실수하면 개인정보가 평문으로 눕는데, 그건 코드 리뷰로 잡기에
     *   너무 조용한 사고다. 암호문은 절대 이 모양이 아니다.
     */
    CONSTRAINT ck_machine_owner_phone_not_plain
        CHECK (phone_encrypted !~ '^[0-9+][0-9 ()-]{6,}$'),

    CONSTRAINT fk_machine_owner_center
        FOREIGN KEY (center_id) REFERENCES official_center (id) ON DELETE SET NULL
);

-- 번호로 업체 찾기 (블라인드 인덱스)
CREATE INDEX ix_machine_owner_phone  ON machine_owner (phone_blind_index)
    WHERE phone_blind_index IS NOT NULL;
-- 상호로 찾기 — 관리 화면의 기본 검색
CREATE INDEX ix_machine_owner_name   ON machine_owner (lower(name));
CREATE INDEX ix_machine_owner_region ON machine_owner (region, name);

COMMENT ON TABLE  machine_owner IS '기구를 산 업체. 연락처는 암호화 저장하며 공개 API 에 절대 내보내지 않는다.';


-- ── 2. 기구에 판매 정보를 붙인다 ───────────────────────────────

-- V8 의 center_id 는 machine_owner.center_id 로 자리를 옮긴다
ALTER TABLE machine_unit DROP CONSTRAINT fk_machine_unit_center;
DROP INDEX ix_machine_unit_center;
ALTER TABLE machine_unit DROP COLUMN center_id;

ALTER TABLE machine_unit
    ADD COLUMN owner_id        BIGINT,
    ADD COLUMN sold_at         DATE,
    ADD COLUMN installed_at    DATE,
    ADD COLUMN warranty_until  DATE;

ALTER TABLE machine_unit
    ADD CONSTRAINT fk_machine_unit_owner
        FOREIGN KEY (owner_id) REFERENCES machine_owner (id) ON DELETE SET NULL;

/*
 * 판매 상태를 하나 더 둔다.
 *
 *   REGISTERED 입고 · 미판매      SOLD      판매됨 · 미출고
 *   SHIPPED    출고               INSTALLED 설치 완료
 *   RECOVERED  회수(중고로 돌아옴) SCRAPPED  폐기
 *   FLAGGED    확인 필요
 *
 * 「판매 유무」 를 sold_at IS NULL 로만 판단하지 않는 이유는, 관리 화면
 * 목록에서 눈으로 훑는 값이 상태 한 칸이기 때문이다. 날짜를 보고
 * 머릿속에서 판정하게 만들면 목록이 읽히지 않는다.
 */
ALTER TABLE machine_unit DROP CONSTRAINT ck_machine_unit_status;
ALTER TABLE machine_unit
    ADD CONSTRAINT ck_machine_unit_status CHECK (status IN
        ('REGISTERED', 'SOLD', 'SHIPPED', 'INSTALLED', 'RECOVERED', 'SCRAPPED', 'FLAGGED'));

-- 팔린 기구는 업체가 있어야 한다. 「팔았는데 누구에게인지 모른다」 를 막는다.
ALTER TABLE machine_unit
    ADD CONSTRAINT ck_machine_unit_sold_has_owner CHECK (
        status IN ('REGISTERED', 'FLAGGED', 'SCRAPPED')
        OR owner_id IS NOT NULL
    );

-- 설치가 판매보다 앞설 수 없다
ALTER TABLE machine_unit
    ADD CONSTRAINT ck_machine_unit_dates CHECK (
        installed_at IS NULL OR sold_at IS NULL OR installed_at >= sold_at
    );

-- 「이 업체가 산 기구 전부」 — 사후 관리의 기본 조회
CREATE INDEX ix_machine_unit_owner ON machine_unit (owner_id, id)
    WHERE owner_id IS NOT NULL;

-- 「이번 달 보증 만료」 — 점검 영업의 근거
CREATE INDEX ix_machine_unit_warranty ON machine_unit (warranty_until)
    WHERE warranty_until IS NOT NULL;


-- ── 3. 사후 관리 이력 ──────────────────────────────────────────
--
-- 기구 한 대에 무슨 일이 있었는지. 중고로 돌아왔을 때 이 이력이
-- 그대로 「정비 내역」 이 된다 (/used 가 약속하는 그것이다).

CREATE TABLE machine_service (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    machine_unit_id BIGINT       NOT NULL,

    --   INSPECTION 정기 점검   REPAIR 수리      PART 부품 교체
    --   MOVE       이전 설치   CLAIM  보증 청구
    kind            VARCHAR(20)  NOT NULL,

    happened_on     DATE         NOT NULL,
    summary         VARCHAR(300) NOT NULL DEFAULT '',
    cost_krw        INTEGER,

    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT machine_service_pkey PRIMARY KEY (id),
    CONSTRAINT ck_machine_service_kind CHECK (kind IN
        ('INSPECTION', 'REPAIR', 'PART', 'MOVE', 'CLAIM')),
    CONSTRAINT ck_machine_service_cost CHECK (cost_krw IS NULL OR cost_krw >= 0),
    CONSTRAINT fk_machine_service_unit
        FOREIGN KEY (machine_unit_id) REFERENCES machine_unit (id) ON DELETE CASCADE
);

-- 기구 상세의 「이력」 — 최신순
CREATE INDEX ix_machine_service_unit ON machine_service (machine_unit_id, happened_on DESC, id DESC);
-- 「이번 달 점검한 것」 · 부품 소모 통계
CREATE INDEX ix_machine_service_when ON machine_service (happened_on DESC, kind);

COMMENT ON TABLE machine_service IS '기구 한 대의 사후 관리 이력. 중고로 회수되면 이것이 정비 내역이 된다.';
